# Generated by Django 4.0.3 on 2022-04-10 00:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=255)),
                ('subject', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='description',
            name='detalis',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
